---
  - name: Wait for SSH to come up
    wait_for: port=22 timeout=320 state=started

  - name: Add the Service Fabric APT Repo
    apt_repository: repo='deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/servicefabric/ trusty main' state=present

  - name: Add the Service Fabric APT Key
    apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893

  - name: Add Ubuntu Keyserver
    apt_key: keyserver=keyserver.ubuntu.com id=68576280

  - name: Add the Nodejs APT Repo
    apt_repository: repo='deb https://deb.nodesource.com/node_4.x trusty main' state=present

  - name: Add the Nodejs APT Src Repo
    apt_repository: repo='deb-src https://deb.nodesource.com/node_4.x trusty main' state=present

  - name: Update APT Cache
    apt: update_cache=yes

  - name: Gen Random Password
    local_action: shell openssl passwd -1 -in /dev/urandom | head -1
    register: gend_password
    become: False
    tags:
      - fabric_users

  - name: Set password for default accounts b/c we will have PAM turned off (run the playbook with --extra-vars “password=")
    user: name={{ item }} password='{{ gend_password['stdout'] }}'
    with_items:
      - ubuntu
      - sfuser

  - name: Turn off password required pam (this is bad)
    shell: sed -i 's/nullok_secure/nullok/' /etc/pam.d/common-auth

  - name: Apply Insecure sshd_config
    copy: src="{{ role_path }}/files/sshd_config" dest=/etc/ssh/sshd_config owner=0 group=0 mode=0644
    notify:
      - restart sshd

  - meta: flush_handlers

  - name: Install Nodejs, OpenSSH Server and Client, Docker
    apt: name={{item}}
    with_items:
       - nodejs
       - openssh-server
       - openssh-client
       - docker.io

  - name: Open firewall for cluster communication
    ufw: rule=allow
    with_items:
      - 30001:35000
      - 19000:19100

  - name: Install Service Fabric SDK
    raw: yes y | sudo apt-get install servicefabricsdk -y

  - name: Generate and Copy Cluster Manifest
    template: src="{{ role_path }}/templates/manifest.xml.j2" dest=/opt/microsoft/sdk/servicefabric/clustersetup/nonsecure/servicefabric-scalemin.xml mode=0644

  - name: Run SDK Setup
    raw: sudo /opt/microsoft/sdk/servicefabric/sdksetup.sh

  - name: Run Cluster Setup
    raw: cd /opt/microsoft/sdk/servicefabric/clustersetup && sudo ./devclustersetup.sh
