---
  - name: Create security group
    ec2_group:
      name: "{{aws_tag}}"
      description: "A Security group"
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: basic_firewall

  ### Create Amazon EC2 key pair
  - name: Amazon EC2 | Create Key Pair
    ec2_key:
      name: "{{ key_name }}"
      region: "{{ aws_region }}"
      key_material: "{{ item }}"
    with_file: ~/.ssh/id_rsa.pub

  - name: create an EC2 instance
    ec2:
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      group_id: "{{basic_firewall.group_id}}"
      instance_type: "{{instance_type}}"
      image: "{{ami_id}}"
      wait: yes
      instance_tags:
        Name: "{{aws_tag}}"
      count_tag:
        Name: "{{aws_tag}}"
      exact_count: "{{ instance_count }}"
    register: ec2_demo

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_dns_name }} groups=fabric_hosts
    with_items: '{{ec2_demo.instances}}'

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ec2_demo.instances}}'

  - name: Refresh in-memory EC2 cache
    meta: refresh_inventory
